### ISSUE TITLE
There are no mapings for Tablecloth (forge + spigot 1.12.2)

### ISSUE THREAD

**Issue by CKATEPTb** [webbukkit/dynmap#2471]
## FEATURE REQUEST
- [ ] I would like to propose an additional feature.
- [ ] I would like to propose a config change.
- [ ] I would like to request mod support.
- [ ] I would like to propose another change.

- [ ] I have searched the wiki and confirmed that this feature is not already implemented.

## MOD INFORMATION
download tablecloth - https://m.mega.dp.ua/ez7HEfC

**Comment by FedUpWith-Tech** [comment]
please use the dynmap-blockscan issue tracker
